//////
/// don't edit! auto-generated by docc: jpgenc.vh
////////////////////////////////////////////////////////////
`ifdef  jpgenc_vh
`else
`define jpgenc_vh (){}



//////
/// 
/// $INTERFACE bitsEncPar              flat             (4,4)
///     # # ----------------------------------------------------------
///     @ 0x00000                      (P)
///               %unsigned 8  arg                       
///                                    ###
///                                    * EC function argument
///                                    ###
///               %unsigned 8  id                        
///                                    ###
///                                    * Function or table ID, msb==1 means “no emulation byte insertion
///                                    ###
///                                    : void                      0x0
///                                                 ###
///                                                 * Shall be ignored
///                                                 ###
///                                    : disEmul                   0x1
///                                                 ###
///                                                 * Emulation byte insertion disable/enable
///                                                 * copDat[0] == 1:   disable emulation byte insertion.
///                                                 * CopDat[0] == 0: enable emulation byte insertion
///                                                 ###
///                                    : bPtr                      0x2
///                                                 ###
///                                                 * No arguments.
///                                                 * Return 32b bit-Ptr which not includes emulation-insert bytes.
///                                                 ###
///                                    : flush                     0x3
///                                                 ###
///                                                 * No arguments. Flush pBunnnf stream to strmOut FiFo(Align to 8 bytes boundary). Return current 29b byte-Ptr, including emulation-insert bytes but not flush filling bytes.
///                                                 ###
///                                    : putBits                   0x4
///                                                 ###
///                                                 * 'arg' = 0~16.
///                                                 * Put bits: copData[arg-1:0].
///                                                 ###
///                                    : EG0                       0x5
///                                                 ###
///                                                 * 0th order Exp-Golomb code: copData[15:0]
///                                                 ###
///                                    : signedEG0                 0x6
///                                                 ###
///                                                 * Signed 0th order Exp-Golomb code: (signed) copData[15:0]
///                                                 ###
///                                    : byteAlign                 0x7
///                                    : auto                      0x8
///                                                 ###
///                                                 * Automatically encoding codewords: (arg, copData[15:0])
///                                                 ###
///               %%        16         # Stuffing bits...
///     # # ----------------------------------------------------------
/// $ENDOFINTERFACE  # size:       4B, bits:      32b, padding:     0B
////////////////////////////////////////////////////////////
`ifdef  vh_bitsEncPar
`else
`define vh_bitsEncPar (){}

    `define     AR_bitsEncPar                                  1
    `define     AB_bitsEncPar                                  2
    `define sizeof_bitsEncPar                                  4
    ///////////////////////////////////////////////////////////

    `define   MSb32bitsEncPar_arg                               7
    `define   LSb32bitsEncPar_arg                                 0
    `define    BF32bitsEncPar_arg                               7:0
    `define       bbitsEncPar_arg                              8

    `define   MSb32bitsEncPar_id                               15
    `define   LSb32bitsEncPar_id                                  8
    `define    BF32bitsEncPar_id                               15:8
    `define       bbitsEncPar_id                               8
    `define        bitsEncPar_id_void                                        8'h0
    `define        bitsEncPar_id_disEmul                                     8'h1
    `define        bitsEncPar_id_bPtr                                        8'h2
    `define        bitsEncPar_id_flush                                       8'h3
    `define        bitsEncPar_id_putBits                                     8'h4
    `define        bitsEncPar_id_EG0                                         8'h5
    `define        bitsEncPar_id_signedEG0                                   8'h6
    `define        bitsEncPar_id_byteAlign                                   8'h7
    `define        bitsEncPar_id_auto                                        8'h8
    ///////////////////////////////////////////////////////////

//////
/// Flattening...
////////////////////////////////////////////////////////////
    `define     TW_bitsEncPar                                  3
    `define     TB_bitsEncPar                                  32

    ///////////////////////////////////////////////////////////
    `define     IA_bitsEncPar                                  2'h0
    `define     IR_bitsEncPar                                     31:0
    `define    SEL_bitsEncPar                                      2:0

    ///////////////////////////////////////////////////////////

    `define    SEL_bitsEncPar_u_arg                            0
    `define    MSb_bitsEncPar_u_arg                                7
    `define    LSb_bitsEncPar_u_arg                                  0
    `define     BF_bitsEncPar_u_arg                                7:0

    `define    SEL_bitsEncPar_u_id                             1
    `define    MSb_bitsEncPar_u_id                                15
    `define    LSb_bitsEncPar_u_id                                   8
    `define     BF_bitsEncPar_u_id                                15:8

`endif
//////
/// ENDOFINTERFACE: bitsEncPar
////////////////////////////////////////////////////////////

//////
/// 
/// $INTERFACE JPGENC                  biu              (4,4)
///     # # ----------------------------------------------------------
///     @ 0x00000 CFG                  (P)
///               ###
///               * configuration
///               ###
///               %unsigned 1  inMode                    0x0
///                                    : lbuf                      0x0
///                                    : img                       0x1
///                                                 ###
///                                                 * Image is stored in DRAM or just buffered in DRAM line buffer
///                                                 ###
///               %unsigned 2  lbufDep                   0x2
///                                    ###
///                                    * Line buffer ( LB ) depth
///                                    * 2'b00 : LB x 16
///                                    * 2'b01 : LB x 32
///                                    * 2'b10 : LB x 64
///                                    * 2'b11 : LB x 128
///                                    ###
///               %unsigned 5  srcSel                    0x0
///                                    ###
///                                    * Source select signal
///                                    ###
///               %unsigned 8  offsetX                   
///                                    ###
///                                    * Digital anti shake output offset X
///                                    ###
///               %unsigned 8  offsetY                   
///                                    ###
///                                    * Digital anti shake output offset Y
///                                    ###
///               %%        8          # Stuffing bits...
///     @ 0x00004 SIZE                 (P)
///               ###
///               * (Valid) image window size definition
///               ###
///               %unsigned 12 width                     
///                                    ###
///                                    * Width : the valid pixels of the input image
///                                    ###
///               %%        4          # Stuffing bits...
///               %unsigned 12 height                    
///                                    ###
///                                    * Height : the valid row of the input image
///                                    ###
///               %%        4          # Stuffing bits...
///     @ 0x00008 MBSIZE               (P)
///               %unsigned 8  mbWidth                   
///                                    ###
///                                    * MbWidth : the output image size
///                                    * mbWidth = out_width[11:4] + |out_width[3:0]
///                                    ###
///               %unsigned 8  mbHeight                  
///                                    ###
///                                    * MbHeight : the output image size
///                                    * mbHeight = out_height[11:4] + |out_height[3:0]
///                                    ###
///               %unsigned 16 mbTotal                   
///                                    ###
///                                    * Total MB number for output :
///                                    * mbTotal    = mbWidth x mbHeight
///                                    ###
///     @ 0x0000C STRIDE               (P)
///               ###
///               * Unit : 16Byte
///               ###
///               %unsigned 8  stride                    
///                                    ###
///                                    * Each row of image may has odd number of pixels, each row of image is required to be at least 16-byte aligned, stride is the aligned width of image
///                                    ###
///               %%        24         # Stuffing bits...
///     @ 0x00010 QMTX0                (P)
///               ###
///               * Quantization Matrix Coefficient write data 0
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x00014 QMTX1                (P)
///               ###
///               * Quantization Matrix Coefficient write data 1
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x00018 QMTX2                (P)
///               ###
///               * Quantization Matrix Coefficient write data 2
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x0001C QMTX3                (P)
///               ###
///               * Quantization Matrix Coefficient write data 3
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x00020 QMTX4                (P)
///               ###
///               * Quantization Matrix Coefficient write data 4
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x00024 QMTX5                (P)
///               ###
///               * Quantization Matrix Coefficient write data 5
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x00028 QMTX6                (P)
///               ###
///               * Quantization Matrix Coefficient write data 6
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x0002C QMTX7                (P)
///               ###
///               * Quantization Matrix Coefficient write data 7
///               ###
///               %unsigned 32 qmtx                      
///     @ 0x00030 QMTXW                (P)
///               ###
///               * Quantization Matrix Coefficient write command
///               ###
///               %unsigned 1  qmtxWe                    
///               %unsigned 3  qmtxWa                    
///                                    ###
///                                    * 256-bits Quantization Matrix Coefficient x 32 will be stored in sram
///                                    ###
///               %%        28         # Stuffing bits...
///     @ 0x00034 BUFY                 (P)
///               ###
///               * Input Buffer Base Addresses Y
///               ###
///               %unsigned 32 addrY                     
///                                    ###
///                                    * Input Y ( raw ) buffer address in 16-byte unit
///                                    ###
///     @ 0x00038 BUFUV                (P)
///               ###
///               * Input Buffer Base Addresses UV
///               ###
///               %unsigned 32 addrUV                    
///                                    ###
///                                    * Input UV ( raw ) buffer address in 16-byte unit
///                                    ###
///     @ 0x0003C BUFO                 (P)
///               ###
///               * Output Buffer Base Addresses
///               ###
///               %unsigned 32 addrO                     
///                                    ###
///                                    * Output ( bit stream ) buffer address in 16-byte uint
///                                    ###
///     @ 0x00040 START                (RW)
///               ###
///               * Read value is busy status of JPGENC, Write '1' to kickoff when it is not busy
///               ###
///               %unsigned 1  en                        0x0
///               %%        31         # Stuffing bits...
///     @ 0x00044 CTRL                 (WOC-)
///               ###
///               * Write 1 to commit a new configuration. Self-cleared.
///               * Note : one commit operation must be executed before START.en is set to 1
///               ###
///               %unsigned 1  commit                    
///               %%        31         # Stuffing bits...
///     @ 0x00048 INTEB                (P)
///               ###
///               * Unit : 256Byte
///               ###
///               %unsigned 4  enoughByte                0x8
///                                    ###
///                                    * Interrupt enough : when enough byte ( n ) has been encoded since last interrupt, new interrupt will be triggered for low latency mode, interrupt count per second must be considered based on CPU performance
///                                    * n = 256 x ( 2 ^ reg_value )
///                                    * 0x0 : n = 256 Bytes
///                                    * ...
///                                    * 0x8 : n = 64 kBytes
///                                    * ...
///                                    * 0xF : n = 8 MBytes
///                                    ###
///               %%        28         # Stuffing bits...
///     @ 0x0004C INTEN                (P)
///               %unsigned 1  eb                        0x0
///                                    : disable                   0x0
///                                    : enable                    0x1
///                                                 ###
///                                                 * Interrupt enough byte : when enough byte has been encoded, interrupt will be triggered for low latency mode
///                                                 ###
///               %unsigned 1  eof                       0x1
///                                    : disable                   0x0
///                                    : enable                    0x1
///                                                 ###
///                                                 * Interrupt end of frame
///                                                 ###
///               %unsigned 1  over                      0x0
///                                    : disable                   0x0
///                                    : enable                    0x1
///                                                 ###
///                                                 * Interrupt dram line buffer overflow
///                                                 ###
///               %%        29         # Stuffing bits...
///     @ 0x00050 INT                  (WOC-)
///               %unsigned 1  eof                       0x0
///               %unsigned 1  enough                    0x0
///               %unsigned 1  over                      0x0
///               %%        29         # Stuffing bits...
///     @ 0x00054 SLEN                 (R-)
///               ###
///               * Output stream length ( unit : byte )
///               ###
///               %unsigned 32 slen                      
///                                    ###
///                                    * slen means count which bytes has been written into dram
///                                    ###
///     @ 0x00058 SWRST                (WOC-)
///               ###
///               * Manual software synchronous reset.
///               ###
///               %unsigned 1  clear                     0x0
///               %%        31         # Stuffing bits...
///     # # ----------------------------------------------------------
/// $ENDOFINTERFACE  # size:      92B, bits:     493b, padding:     0B
////////////////////////////////////////////////////////////
`ifdef  vh_JPGENC
`else
`define vh_JPGENC (){}

    `define     AR_JPGENC                                      23
    `define     AB_JPGENC                                      7
    `define sizeof_JPGENC                                      92
    ///////////////////////////////////////////////////////////

    `define     RA_JPGENC_CFG                                  7'h0
    `define     RB_JPGENC_CFG                                  24
    `define    MSK_JPGENC_CFG                                  32'h00FFFFFF

    `define     dftJPGENC_CFG_inMode                            1'h0
    `define   MSb32JPGENC_CFG_inMode                            0
    `define   LSb32JPGENC_CFG_inMode                              0
    `define    BF32JPGENC_CFG_inMode                            0:0
    `define       bJPGENC_CFG_inMode                           1
    `define        JPGENC_CFG_inMode_lbuf                                    1'h0
    `define        JPGENC_CFG_inMode_img                                     1'h1

    `define     dftJPGENC_CFG_lbufDep                           2'h2
    `define   MSb32JPGENC_CFG_lbufDep                           2
    `define   LSb32JPGENC_CFG_lbufDep                             1
    `define    BF32JPGENC_CFG_lbufDep                           2:1
    `define       bJPGENC_CFG_lbufDep                          2

    `define     dftJPGENC_CFG_srcSel                            5'h0
    `define   MSb32JPGENC_CFG_srcSel                            7
    `define   LSb32JPGENC_CFG_srcSel                              3
    `define    BF32JPGENC_CFG_srcSel                            7:3
    `define       bJPGENC_CFG_srcSel                           5

    `define   MSb32JPGENC_CFG_offsetX                          15
    `define   LSb32JPGENC_CFG_offsetX                             8
    `define    BF32JPGENC_CFG_offsetX                          15:8
    `define       bJPGENC_CFG_offsetX                          8

    `define   MSb32JPGENC_CFG_offsetY                          23
    `define   LSb32JPGENC_CFG_offsetY                             16
    `define    BF32JPGENC_CFG_offsetY                          23:16
    `define       bJPGENC_CFG_offsetY                          8
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_SIZE                                 7'h4
    `define     RB_JPGENC_SIZE                                 28
    `define    MSK_JPGENC_SIZE                                 32'h0FFF0FFF

    `define   MSb32JPGENC_SIZE_width                           11
    `define   LSb32JPGENC_SIZE_width                              0
    `define    BF32JPGENC_SIZE_width                           11:0
    `define       bJPGENC_SIZE_width                           12

    `define   MSb32JPGENC_SIZE_height                          27
    `define   LSb32JPGENC_SIZE_height                             16
    `define    BF32JPGENC_SIZE_height                          27:16
    `define       bJPGENC_SIZE_height                          12
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_MBSIZE                               7'h8
    `define     RB_JPGENC_MBSIZE                               32
    `define    MSK_JPGENC_MBSIZE                               32'hFFFFFFFF

    `define   MSb32JPGENC_MBSIZE_mbWidth                        7
    `define   LSb32JPGENC_MBSIZE_mbWidth                          0
    `define    BF32JPGENC_MBSIZE_mbWidth                        7:0
    `define       bJPGENC_MBSIZE_mbWidth                       8

    `define   MSb32JPGENC_MBSIZE_mbHeight                      15
    `define   LSb32JPGENC_MBSIZE_mbHeight                         8
    `define    BF32JPGENC_MBSIZE_mbHeight                      15:8
    `define       bJPGENC_MBSIZE_mbHeight                      8

    `define   MSb32JPGENC_MBSIZE_mbTotal                       31
    `define   LSb32JPGENC_MBSIZE_mbTotal                          16
    `define    BF32JPGENC_MBSIZE_mbTotal                       31:16
    `define       bJPGENC_MBSIZE_mbTotal                       16
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_STRIDE                               7'hC
    `define     RB_JPGENC_STRIDE                               8
    `define    MSK_JPGENC_STRIDE                               32'h000000FF

    `define   MSb32JPGENC_STRIDE_stride                         7
    `define   LSb32JPGENC_STRIDE_stride                           0
    `define    BF32JPGENC_STRIDE_stride                         7:0
    `define       bJPGENC_STRIDE_stride                        8
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX0                                7'h10
    `define     RB_JPGENC_QMTX0                                32
    `define    MSK_JPGENC_QMTX0                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX0_qmtx                           31
    `define   LSb32JPGENC_QMTX0_qmtx                              0
    `define    BF32JPGENC_QMTX0_qmtx                           31:0
    `define       bJPGENC_QMTX0_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX1                                7'h14
    `define     RB_JPGENC_QMTX1                                32
    `define    MSK_JPGENC_QMTX1                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX1_qmtx                           31
    `define   LSb32JPGENC_QMTX1_qmtx                              0
    `define    BF32JPGENC_QMTX1_qmtx                           31:0
    `define       bJPGENC_QMTX1_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX2                                7'h18
    `define     RB_JPGENC_QMTX2                                32
    `define    MSK_JPGENC_QMTX2                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX2_qmtx                           31
    `define   LSb32JPGENC_QMTX2_qmtx                              0
    `define    BF32JPGENC_QMTX2_qmtx                           31:0
    `define       bJPGENC_QMTX2_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX3                                7'h1C
    `define     RB_JPGENC_QMTX3                                32
    `define    MSK_JPGENC_QMTX3                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX3_qmtx                           31
    `define   LSb32JPGENC_QMTX3_qmtx                              0
    `define    BF32JPGENC_QMTX3_qmtx                           31:0
    `define       bJPGENC_QMTX3_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX4                                7'h20
    `define     RB_JPGENC_QMTX4                                32
    `define    MSK_JPGENC_QMTX4                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX4_qmtx                           31
    `define   LSb32JPGENC_QMTX4_qmtx                              0
    `define    BF32JPGENC_QMTX4_qmtx                           31:0
    `define       bJPGENC_QMTX4_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX5                                7'h24
    `define     RB_JPGENC_QMTX5                                32
    `define    MSK_JPGENC_QMTX5                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX5_qmtx                           31
    `define   LSb32JPGENC_QMTX5_qmtx                              0
    `define    BF32JPGENC_QMTX5_qmtx                           31:0
    `define       bJPGENC_QMTX5_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX6                                7'h28
    `define     RB_JPGENC_QMTX6                                32
    `define    MSK_JPGENC_QMTX6                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX6_qmtx                           31
    `define   LSb32JPGENC_QMTX6_qmtx                              0
    `define    BF32JPGENC_QMTX6_qmtx                           31:0
    `define       bJPGENC_QMTX6_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTX7                                7'h2C
    `define     RB_JPGENC_QMTX7                                32
    `define    MSK_JPGENC_QMTX7                                32'hFFFFFFFF

    `define   MSb32JPGENC_QMTX7_qmtx                           31
    `define   LSb32JPGENC_QMTX7_qmtx                              0
    `define    BF32JPGENC_QMTX7_qmtx                           31:0
    `define       bJPGENC_QMTX7_qmtx                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_QMTXW                                7'h30
    `define     RB_JPGENC_QMTXW                                4
    `define    MSK_JPGENC_QMTXW                                32'h0000000F

    `define   MSb32JPGENC_QMTXW_qmtxWe                          0
    `define   LSb32JPGENC_QMTXW_qmtxWe                            0
    `define    BF32JPGENC_QMTXW_qmtxWe                          0:0
    `define       bJPGENC_QMTXW_qmtxWe                         1

    `define   MSb32JPGENC_QMTXW_qmtxWa                          3
    `define   LSb32JPGENC_QMTXW_qmtxWa                            1
    `define    BF32JPGENC_QMTXW_qmtxWa                          3:1
    `define       bJPGENC_QMTXW_qmtxWa                         3
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_BUFY                                 7'h34
    `define     RB_JPGENC_BUFY                                 32
    `define    MSK_JPGENC_BUFY                                 32'hFFFFFFFF

    `define   MSb32JPGENC_BUFY_addrY                           31
    `define   LSb32JPGENC_BUFY_addrY                              0
    `define    BF32JPGENC_BUFY_addrY                           31:0
    `define       bJPGENC_BUFY_addrY                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_BUFUV                                7'h38
    `define     RB_JPGENC_BUFUV                                32
    `define    MSK_JPGENC_BUFUV                                32'hFFFFFFFF

    `define   MSb32JPGENC_BUFUV_addrUV                         31
    `define   LSb32JPGENC_BUFUV_addrUV                            0
    `define    BF32JPGENC_BUFUV_addrUV                         31:0
    `define       bJPGENC_BUFUV_addrUV                         32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_BUFO                                 7'h3C
    `define     RB_JPGENC_BUFO                                 32
    `define    MSK_JPGENC_BUFO                                 32'hFFFFFFFF

    `define   MSb32JPGENC_BUFO_addrO                           31
    `define   LSb32JPGENC_BUFO_addrO                              0
    `define    BF32JPGENC_BUFO_addrO                           31:0
    `define       bJPGENC_BUFO_addrO                           32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_START                                7'h40
    `define     RB_JPGENC_START                                1
    `define    MSK_JPGENC_START                                32'h00000001

    `define     dftJPGENC_START_en                              1'h0
    `define   MSb32JPGENC_START_en                              0
    `define   LSb32JPGENC_START_en                                0
    `define    BF32JPGENC_START_en                              0:0
    `define       bJPGENC_START_en                             1
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_CTRL                                 7'h44
    `define     RB_JPGENC_CTRL                                 1
    `define    MSK_JPGENC_CTRL                                 32'h00000001

    `define   MSb32JPGENC_CTRL_commit                           0
    `define   LSb32JPGENC_CTRL_commit                             0
    `define    BF32JPGENC_CTRL_commit                           0:0
    `define       bJPGENC_CTRL_commit                          1
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_INTEB                                7'h48
    `define     RB_JPGENC_INTEB                                4
    `define    MSK_JPGENC_INTEB                                32'h0000000F

    `define     dftJPGENC_INTEB_enoughByte                      4'h8
    `define   MSb32JPGENC_INTEB_enoughByte                      3
    `define   LSb32JPGENC_INTEB_enoughByte                        0
    `define    BF32JPGENC_INTEB_enoughByte                      3:0
    `define       bJPGENC_INTEB_enoughByte                     4
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_INTEN                                7'h4C
    `define     RB_JPGENC_INTEN                                3
    `define    MSK_JPGENC_INTEN                                32'h00000007

    `define     dftJPGENC_INTEN_eb                              1'h0
    `define   MSb32JPGENC_INTEN_eb                              0
    `define   LSb32JPGENC_INTEN_eb                                0
    `define    BF32JPGENC_INTEN_eb                              0:0
    `define       bJPGENC_INTEN_eb                             1
    `define        JPGENC_INTEN_eb_disable                                   1'h0
    `define        JPGENC_INTEN_eb_enable                                    1'h1

    `define     dftJPGENC_INTEN_eof                             1'h1
    `define   MSb32JPGENC_INTEN_eof                             1
    `define   LSb32JPGENC_INTEN_eof                               1
    `define    BF32JPGENC_INTEN_eof                             1:1
    `define       bJPGENC_INTEN_eof                            1
    `define        JPGENC_INTEN_eof_disable                                  1'h0
    `define        JPGENC_INTEN_eof_enable                                   1'h1

    `define     dftJPGENC_INTEN_over                            1'h0
    `define   MSb32JPGENC_INTEN_over                            2
    `define   LSb32JPGENC_INTEN_over                              2
    `define    BF32JPGENC_INTEN_over                            2:2
    `define       bJPGENC_INTEN_over                           1
    `define        JPGENC_INTEN_over_disable                                 1'h0
    `define        JPGENC_INTEN_over_enable                                  1'h1
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_INT                                  7'h50
    `define     RB_JPGENC_INT                                  3
    `define    MSK_JPGENC_INT                                  32'h00000007

    `define     dftJPGENC_INT_eof                               1'h0
    `define   MSb32JPGENC_INT_eof                               0
    `define   LSb32JPGENC_INT_eof                                 0
    `define    BF32JPGENC_INT_eof                               0:0
    `define       bJPGENC_INT_eof                              1

    `define     dftJPGENC_INT_enough                            1'h0
    `define   MSb32JPGENC_INT_enough                            1
    `define   LSb32JPGENC_INT_enough                              1
    `define    BF32JPGENC_INT_enough                            1:1
    `define       bJPGENC_INT_enough                           1

    `define     dftJPGENC_INT_over                              1'h0
    `define   MSb32JPGENC_INT_over                              2
    `define   LSb32JPGENC_INT_over                                2
    `define    BF32JPGENC_INT_over                              2:2
    `define       bJPGENC_INT_over                             1
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_SLEN                                 7'h54
    `define     RB_JPGENC_SLEN                                 32
    `define    MSK_JPGENC_SLEN                                 32'hFFFFFFFF

    `define   MSb32JPGENC_SLEN_slen                            31
    `define   LSb32JPGENC_SLEN_slen                               0
    `define    BF32JPGENC_SLEN_slen                            31:0
    `define       bJPGENC_SLEN_slen                            32
    ///////////////////////////////////////////////////////////
    `define     RA_JPGENC_SWRST                                7'h58
    `define     RB_JPGENC_SWRST                                1
    `define    MSK_JPGENC_SWRST                                32'h00000001

    `define     dftJPGENC_SWRST_clear                           1'h0
    `define   MSb32JPGENC_SWRST_clear                           0
    `define   LSb32JPGENC_SWRST_clear                             0
    `define    BF32JPGENC_SWRST_clear                           0:0
    `define       bJPGENC_SWRST_clear                          1
    ///////////////////////////////////////////////////////////

//////
/// Flattening...
////////////////////////////////////////////////////////////
    `define     TW_JPGENC                                      36
    `define     TB_JPGENC                                      493

    ///////////////////////////////////////////////////////////
    `define     IA_JPGENC                                      7'h0
    `define     IR_JPGENC                                        492:0
    `define    SEL_JPGENC                                         35:0

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_CFG                                  7'h0
    `define     FR_JPGENC_CFG                                     23:0
    `define    SEL_JPGENC_CFG                                      4:0

    `define    SEL_JPGENC_uCFG_inMode                          0
    `define    MSb_JPGENC_uCFG_inMode                              0
    `define    LSb_JPGENC_uCFG_inMode                                0
    `define     BF_JPGENC_uCFG_inMode                              0:0

    `define    SEL_JPGENC_uCFG_lbufDep                         1
    `define    MSb_JPGENC_uCFG_lbufDep                             2
    `define    LSb_JPGENC_uCFG_lbufDep                               1
    `define     BF_JPGENC_uCFG_lbufDep                             2:1

    `define    SEL_JPGENC_uCFG_srcSel                          2
    `define    MSb_JPGENC_uCFG_srcSel                              7
    `define    LSb_JPGENC_uCFG_srcSel                                3
    `define     BF_JPGENC_uCFG_srcSel                              7:3

    `define    SEL_JPGENC_uCFG_offsetX                         3
    `define    MSb_JPGENC_uCFG_offsetX                            15
    `define    LSb_JPGENC_uCFG_offsetX                               8
    `define     BF_JPGENC_uCFG_offsetX                            15:8

    `define    SEL_JPGENC_uCFG_offsetY                         4
    `define    MSb_JPGENC_uCFG_offsetY                            23
    `define    LSb_JPGENC_uCFG_offsetY                               16
    `define     BF_JPGENC_uCFG_offsetY                            23:16

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_SIZE                                 7'h4
    `define     FR_JPGENC_SIZE                                    51:24
    `define    SEL_JPGENC_SIZE                                     7:5

    `define    SEL_JPGENC_uSIZE_width                          5
    `define    MSb_JPGENC_uSIZE_width                             35
    `define    LSb_JPGENC_uSIZE_width                                24
    `define     BF_JPGENC_uSIZE_width                             35:24

    `define    SEL_JPGENC_uSIZE_height                         7
    `define    MSb_JPGENC_uSIZE_height                            51
    `define    LSb_JPGENC_uSIZE_height                               40
    `define     BF_JPGENC_uSIZE_height                            51:40

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_MBSIZE                               7'h8
    `define     FR_JPGENC_MBSIZE                                  83:52
    `define    SEL_JPGENC_MBSIZE                                  10:8

    `define    SEL_JPGENC_uMBSIZE_mbWidth                      8
    `define    MSb_JPGENC_uMBSIZE_mbWidth                         59
    `define    LSb_JPGENC_uMBSIZE_mbWidth                            52
    `define     BF_JPGENC_uMBSIZE_mbWidth                         59:52

    `define    SEL_JPGENC_uMBSIZE_mbHeight                     9
    `define    MSb_JPGENC_uMBSIZE_mbHeight                        67
    `define    LSb_JPGENC_uMBSIZE_mbHeight                           60
    `define     BF_JPGENC_uMBSIZE_mbHeight                        67:60

    `define    SEL_JPGENC_uMBSIZE_mbTotal                      10
    `define    MSb_JPGENC_uMBSIZE_mbTotal                         83
    `define    LSb_JPGENC_uMBSIZE_mbTotal                            68
    `define     BF_JPGENC_uMBSIZE_mbTotal                         83:68

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_STRIDE                               7'hC
    `define     FR_JPGENC_STRIDE                                  91:84
    `define    SEL_JPGENC_STRIDE                                  11:11

    `define    SEL_JPGENC_uSTRIDE_stride                       11
    `define    MSb_JPGENC_uSTRIDE_stride                          91
    `define    LSb_JPGENC_uSTRIDE_stride                             84
    `define     BF_JPGENC_uSTRIDE_stride                          91:84

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX0                                7'h10
    `define     FR_JPGENC_QMTX0                                  123:92
    `define    SEL_JPGENC_QMTX0                                   12:12

    `define    SEL_JPGENC_uQMTX0_qmtx                          12
    `define    MSb_JPGENC_uQMTX0_qmtx                            123
    `define    LSb_JPGENC_uQMTX0_qmtx                                92
    `define     BF_JPGENC_uQMTX0_qmtx                            123:92

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX1                                7'h14
    `define     FR_JPGENC_QMTX1                                  155:124
    `define    SEL_JPGENC_QMTX1                                   13:13

    `define    SEL_JPGENC_uQMTX1_qmtx                          13
    `define    MSb_JPGENC_uQMTX1_qmtx                            155
    `define    LSb_JPGENC_uQMTX1_qmtx                                124
    `define     BF_JPGENC_uQMTX1_qmtx                            155:124

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX2                                7'h18
    `define     FR_JPGENC_QMTX2                                  187:156
    `define    SEL_JPGENC_QMTX2                                   14:14

    `define    SEL_JPGENC_uQMTX2_qmtx                          14
    `define    MSb_JPGENC_uQMTX2_qmtx                            187
    `define    LSb_JPGENC_uQMTX2_qmtx                                156
    `define     BF_JPGENC_uQMTX2_qmtx                            187:156

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX3                                7'h1C
    `define     FR_JPGENC_QMTX3                                  219:188
    `define    SEL_JPGENC_QMTX3                                   15:15

    `define    SEL_JPGENC_uQMTX3_qmtx                          15
    `define    MSb_JPGENC_uQMTX3_qmtx                            219
    `define    LSb_JPGENC_uQMTX3_qmtx                                188
    `define     BF_JPGENC_uQMTX3_qmtx                            219:188

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX4                                7'h20
    `define     FR_JPGENC_QMTX4                                  251:220
    `define    SEL_JPGENC_QMTX4                                   16:16

    `define    SEL_JPGENC_uQMTX4_qmtx                          16
    `define    MSb_JPGENC_uQMTX4_qmtx                            251
    `define    LSb_JPGENC_uQMTX4_qmtx                                220
    `define     BF_JPGENC_uQMTX4_qmtx                            251:220

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX5                                7'h24
    `define     FR_JPGENC_QMTX5                                  283:252
    `define    SEL_JPGENC_QMTX5                                   17:17

    `define    SEL_JPGENC_uQMTX5_qmtx                          17
    `define    MSb_JPGENC_uQMTX5_qmtx                            283
    `define    LSb_JPGENC_uQMTX5_qmtx                                252
    `define     BF_JPGENC_uQMTX5_qmtx                            283:252

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX6                                7'h28
    `define     FR_JPGENC_QMTX6                                  315:284
    `define    SEL_JPGENC_QMTX6                                   18:18

    `define    SEL_JPGENC_uQMTX6_qmtx                          18
    `define    MSb_JPGENC_uQMTX6_qmtx                            315
    `define    LSb_JPGENC_uQMTX6_qmtx                                284
    `define     BF_JPGENC_uQMTX6_qmtx                            315:284

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTX7                                7'h2C
    `define     FR_JPGENC_QMTX7                                  347:316
    `define    SEL_JPGENC_QMTX7                                   19:19

    `define    SEL_JPGENC_uQMTX7_qmtx                          19
    `define    MSb_JPGENC_uQMTX7_qmtx                            347
    `define    LSb_JPGENC_uQMTX7_qmtx                                316
    `define     BF_JPGENC_uQMTX7_qmtx                            347:316

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_QMTXW                                7'h30
    `define     FR_JPGENC_QMTXW                                  351:348
    `define    SEL_JPGENC_QMTXW                                   21:20

    `define    SEL_JPGENC_uQMTXW_qmtxWe                        20
    `define    MSb_JPGENC_uQMTXW_qmtxWe                          348
    `define    LSb_JPGENC_uQMTXW_qmtxWe                              348
    `define     BF_JPGENC_uQMTXW_qmtxWe                          348:348

    `define    SEL_JPGENC_uQMTXW_qmtxWa                        21
    `define    MSb_JPGENC_uQMTXW_qmtxWa                          351
    `define    LSb_JPGENC_uQMTXW_qmtxWa                              349
    `define     BF_JPGENC_uQMTXW_qmtxWa                          351:349

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_BUFY                                 7'h34
    `define     FR_JPGENC_BUFY                                   383:352
    `define    SEL_JPGENC_BUFY                                    22:22

    `define    SEL_JPGENC_uBUFY_addrY                          22
    `define    MSb_JPGENC_uBUFY_addrY                            383
    `define    LSb_JPGENC_uBUFY_addrY                                352
    `define     BF_JPGENC_uBUFY_addrY                            383:352

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_BUFUV                                7'h38
    `define     FR_JPGENC_BUFUV                                  415:384
    `define    SEL_JPGENC_BUFUV                                   23:23

    `define    SEL_JPGENC_uBUFUV_addrUV                        23
    `define    MSb_JPGENC_uBUFUV_addrUV                          415
    `define    LSb_JPGENC_uBUFUV_addrUV                              384
    `define     BF_JPGENC_uBUFUV_addrUV                          415:384

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_BUFO                                 7'h3C
    `define     FR_JPGENC_BUFO                                   447:416
    `define    SEL_JPGENC_BUFO                                    24:24

    `define    SEL_JPGENC_uBUFO_addrO                          24
    `define    MSb_JPGENC_uBUFO_addrO                            447
    `define    LSb_JPGENC_uBUFO_addrO                                416
    `define     BF_JPGENC_uBUFO_addrO                            447:416

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_START                                7'h40
    `define     FR_JPGENC_START                                  448:448
    `define    SEL_JPGENC_START                                   25:25

    `define    SEL_JPGENC_uSTART_en                            25
    `define    MSb_JPGENC_uSTART_en                              448
    `define    LSb_JPGENC_uSTART_en                                  448
    `define     BF_JPGENC_uSTART_en                              448:448

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_CTRL                                 7'h44
    `define     FR_JPGENC_CTRL                                   449:449
    `define    SEL_JPGENC_CTRL                                    26:26

    `define    SEL_JPGENC_uCTRL_commit                         26
    `define    MSb_JPGENC_uCTRL_commit                           449
    `define    LSb_JPGENC_uCTRL_commit                               449
    `define     BF_JPGENC_uCTRL_commit                           449:449

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_INTEB                                7'h48
    `define     FR_JPGENC_INTEB                                  453:450
    `define    SEL_JPGENC_INTEB                                   27:27

    `define    SEL_JPGENC_uINTEB_enoughByte                    27
    `define    MSb_JPGENC_uINTEB_enoughByte                      453
    `define    LSb_JPGENC_uINTEB_enoughByte                          450
    `define     BF_JPGENC_uINTEB_enoughByte                      453:450

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_INTEN                                7'h4C
    `define     FR_JPGENC_INTEN                                  456:454
    `define    SEL_JPGENC_INTEN                                   30:28

    `define    SEL_JPGENC_uINTEN_eb                            28
    `define    MSb_JPGENC_uINTEN_eb                              454
    `define    LSb_JPGENC_uINTEN_eb                                  454
    `define     BF_JPGENC_uINTEN_eb                              454:454

    `define    SEL_JPGENC_uINTEN_eof                           29
    `define    MSb_JPGENC_uINTEN_eof                             455
    `define    LSb_JPGENC_uINTEN_eof                                 455
    `define     BF_JPGENC_uINTEN_eof                             455:455

    `define    SEL_JPGENC_uINTEN_over                          30
    `define    MSb_JPGENC_uINTEN_over                            456
    `define    LSb_JPGENC_uINTEN_over                                456
    `define     BF_JPGENC_uINTEN_over                            456:456

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_INT                                  7'h50
    `define     FR_JPGENC_INT                                    459:457
    `define    SEL_JPGENC_INT                                     33:31

    `define    SEL_JPGENC_uINT_eof                             31
    `define    MSb_JPGENC_uINT_eof                               457
    `define    LSb_JPGENC_uINT_eof                                   457
    `define     BF_JPGENC_uINT_eof                               457:457

    `define    SEL_JPGENC_uINT_enough                          32
    `define    MSb_JPGENC_uINT_enough                            458
    `define    LSb_JPGENC_uINT_enough                                458
    `define     BF_JPGENC_uINT_enough                            458:458

    `define    SEL_JPGENC_uINT_over                            33
    `define    MSb_JPGENC_uINT_over                              459
    `define    LSb_JPGENC_uINT_over                                  459
    `define     BF_JPGENC_uINT_over                              459:459

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_SLEN                                 7'h54
    `define     FR_JPGENC_SLEN                                   491:460
    `define    SEL_JPGENC_SLEN                                    34:34

    `define    SEL_JPGENC_uSLEN_slen                           34
    `define    MSb_JPGENC_uSLEN_slen                             491
    `define    LSb_JPGENC_uSLEN_slen                                 460
    `define     BF_JPGENC_uSLEN_slen                             491:460

    ///////////////////////////////////////////////////////////
    `define     FA_JPGENC_SWRST                                7'h58
    `define     FR_JPGENC_SWRST                                  492:492
    `define    SEL_JPGENC_SWRST                                   35:35

    `define    SEL_JPGENC_uSWRST_clear                         35
    `define    MSb_JPGENC_uSWRST_clear                           492
    `define    LSb_JPGENC_uSWRST_clear                               492
    `define     BF_JPGENC_uSWRST_clear                           492:492

`endif
//////
/// ENDOFINTERFACE: JPGENC
////////////////////////////////////////////////////////////



`endif
//////
/// ENDOFFILE: jpgenc.vh
////////////////////////////////////////////////////////////

